"""Public DTO surface for the API and skill contracts.

Definitions live in per-domain modules; this package re-exports the public
names so ``from app.schemas import X`` keeps working regardless of which
domain module owns ``X``.
"""

from app.schemas.calendar import (
    CalendarItemCreate,
    CalendarFeedCreate,
    CalendarFeedRead,
    CalendarItemRead,
    CalendarItemUpdate,
    CalendarReminderRead,
    CalendarSyncResult,
    EventCreate,
    EventRead,
    EventUpdate,
)
from app.schemas.dashboard import DashboardOverview
from app.schemas.finance import (
    AccountCreate,
    AccountRead,
    AccountUpdate,
    BudgetCreate,
    BudgetRead,
    FinanceMonthSummary,
    FinanceTransactionCreate,
    FinanceTransactionRead,
    PatrimoineOverview,
    SavingsGoalCreate,
    SavingsGoalRead,
    SavingsGoalUpdate,
    SubscriptionCreate,
    SubscriptionProjection,
    SubscriptionRead,
    SubscriptionUpdate,
)
from app.schemas.fitness import (
    FitnessMeasurementCreate,
    FitnessMeasurementRead,
    FitnessMeasurementUpdate,
    FitnessExerciseIn,
    FitnessExerciseRead,
    FitnessOverviewRead,
    FitnessSessionComplete,
    FitnessSessionCreate,
    FitnessSessionRead,
    FitnessSessionUpdate,
    FitnessStatsRead,
)
from app.schemas.goals import (
    GoalCreate,
    GoalMilestoneCreate,
    GoalMilestoneRead,
    GoalMilestoneUpdate,
    GoalRead,
    GoalUpdate,
)
from app.schemas.groceries import GroceryItemCreate, GroceryItemRead, GroceryItemUpdate
from app.schemas.habits import HabitCreate, HabitLogCreate, HabitLogRead, HabitRead, HabitUpdate
from app.schemas.linear import LinearIssueCreate, LinearIssueRead, LinearProjectRead, LinearSyncResult
from app.schemas.meal_planning import (
    MealPlanCreate,
    MealPlanConfirmCooked,
    MealPlanConfirmResult,
    MealIngredientRestoreRead,
    MealIngredientConsumptionRead,
    MealCookLogCreate,
    MealPlanRead,
    MealPlanUnconfirmResult,
    MealPlanUpdate,
    RecipeCookRequest,
    RecipeCookResult,
    RecipeUncookResult,
    MissingIngredientRead,
    RecipeCreate,
    RecipeIngredientIn,
    RecipeIngredientRead,
    RecipeRead,
    RecipeUpdate,
)
from app.schemas.notes import NoteCreate, NoteRead, NoteUpdate
from app.schemas.pantry import (
    PantryConsume,
    PantryItemCreate,
    PantryItemRead,
    PantryItemUpdate,
    PantryOverview,
)
from app.schemas.skills import SkillExecuteRequest, SkillExecuteResponse
from app.schemas.supermarket import (
    AuchanOfferingContext,
    AuchanStoreSelectionRequest,
    SupermarketCartItemAdd,
    SupermarketCartItemRead,
    SupermarketCartItemUpdate,
    SupermarketCartRead,
    SupermarketCartStatusUpdate,
    SupermarketConnectionImport,
    SupermarketConnectionRead,
    SupermarketCredentials,
    SupermarketMappingCreate,
    SupermarketMappingRead,
    SupermarketSearchRequest,
    SupermarketSearchResult,
    SupermarketStoreRead,
    SupermarketStoreSelectionRead,
    SupermarketStoreSelectionRequest,
)
from app.schemas.tasks import TaskCreate, TaskRead, TaskSubtask, TaskUpdate
from app.schemas.video import TranscriptSegmentRead, VideoSourceRead, VideoSourceRequest

__all__ = [
    "AccountCreate",
    "AccountRead",
    "AccountUpdate",
    "BudgetCreate",
    "BudgetRead",
    "CalendarItemCreate",
    "CalendarFeedCreate",
    "CalendarFeedRead",
    "CalendarItemRead",
    "CalendarItemUpdate",
    "CalendarReminderRead",
    "CalendarSyncResult",
    "DashboardOverview",
    "EventCreate",
    "EventRead",
    "EventUpdate",
    "FinanceMonthSummary",
    "FinanceTransactionCreate",
    "FinanceTransactionRead",
    "FitnessMeasurementCreate",
    "FitnessMeasurementRead",
    "FitnessMeasurementUpdate",
    "FitnessExerciseIn",
    "FitnessExerciseRead",
    "FitnessOverviewRead",
    "FitnessSessionComplete",
    "FitnessSessionCreate",
    "FitnessSessionRead",
    "FitnessSessionUpdate",
    "FitnessStatsRead",
    "GoalCreate",
    "GoalMilestoneCreate",
    "GoalMilestoneRead",
    "GoalMilestoneUpdate",
    "GoalRead",
    "GoalUpdate",
    "GroceryItemCreate",
    "GroceryItemRead",
    "GroceryItemUpdate",
    "HabitCreate",
    "HabitLogCreate",
    "HabitLogRead",
    "HabitRead",
    "HabitUpdate",
    "LinearIssueCreate",
    "LinearIssueRead",
    "LinearProjectRead",
    "LinearSyncResult",
    "MealPlanCreate",
    "MealPlanConfirmCooked",
    "MealPlanConfirmResult",
    "MealIngredientRestoreRead",
    "MealIngredientConsumptionRead",
    "MealCookLogCreate",
    "MealPlanRead",
    "MealPlanUnconfirmResult",
    "MealPlanUpdate",
    "RecipeCookRequest",
    "RecipeCookResult",
    "RecipeUncookResult",
    "MissingIngredientRead",
    "NoteCreate",
    "NoteRead",
    "NoteUpdate",
    "PantryConsume",
    "PantryItemCreate",
    "PantryItemRead",
    "PantryItemUpdate",
    "PantryOverview",
    "PatrimoineOverview",
    "RecipeCreate",
    "RecipeIngredientIn",
    "RecipeIngredientRead",
    "RecipeRead",
    "RecipeUpdate",
    "TranscriptSegmentRead",
    "VideoSourceRead",
    "VideoSourceRequest",
    "SkillExecuteRequest",
    "SkillExecuteResponse",
    "SavingsGoalCreate",
    "SavingsGoalRead",
    "SavingsGoalUpdate",
    "AuchanOfferingContext",
    "AuchanStoreSelectionRequest",
    "SupermarketCartItemAdd",
    "SupermarketCartItemRead",
    "SupermarketCartItemUpdate",
    "SupermarketCartRead",
    "SupermarketCartStatusUpdate",
    "SupermarketConnectionImport",
    "SupermarketConnectionRead",
    "SupermarketCredentials",
    "SupermarketMappingCreate",
    "SupermarketMappingRead",
    "SupermarketSearchRequest",
    "SupermarketSearchResult",
    "SupermarketStoreRead",
    "SupermarketStoreSelectionRead",
    "SupermarketStoreSelectionRequest",
    "SubscriptionCreate",
    "SubscriptionProjection",
    "SubscriptionRead",
    "SubscriptionUpdate",
    "TaskCreate",
    "TaskRead",
    "TaskSubtask",
    "TaskUpdate",
]
