"""Backwards-compatible facade over the active per-domain schema modules."""

from app.schemas.groceries import GroceryItemCreate, GroceryItemRead, GroceryItemUpdate
from app.schemas.meal_planning import (
    MealCookLogCreate,
    MealIngredientConsumptionRead,
    MealIngredientRestoreRead,
    MealPlanConfirmCooked,
    MealPlanConfirmResult,
    MealPlanCreate,
    MealPlanRead,
    MealPlanUnconfirmResult,
    MealPlanUpdate,
    MissingIngredientRead,
    RecipeCookRequest,
    RecipeCookResult,
    RecipeCreate,
    RecipeIngredientIn,
    RecipeIngredientRead,
    RecipeRead,
    RecipeUncookResult,
    RecipeUpdate,
)
from app.schemas.pantry import (
    PantryConsume,
    PantryItemCreate,
    PantryItemRead,
    PantryItemUpdate,
    PantryOverview,
)
from app.schemas.skills import SkillExecuteRequest, SkillExecuteResponse
from app.schemas.supermarket import (
    SupermarketConnectionImport,
    SupermarketConnectionRead,
    SupermarketMappingCreate,
    SupermarketMappingRead,
    SupermarketSearchRequest,
    SupermarketSearchResult,
    SupermarketStoreRead,
)

__all__ = [
    "GroceryItemCreate",
    "GroceryItemRead",
    "GroceryItemUpdate",
    "MealPlanCreate",
    "MealPlanConfirmCooked",
    "MealPlanConfirmResult",
    "MealIngredientRestoreRead",
    "MealIngredientConsumptionRead",
    "MealCookLogCreate",
    "MealPlanRead",
    "MealPlanUnconfirmResult",
    "MealPlanUpdate",
    "RecipeCookRequest",
    "RecipeCookResult",
    "RecipeUncookResult",
    "MissingIngredientRead",
    "PantryConsume",
    "PantryItemCreate",
    "PantryItemRead",
    "PantryItemUpdate",
    "PantryOverview",
    "RecipeCreate",
    "RecipeIngredientIn",
    "RecipeIngredientRead",
    "RecipeRead",
    "RecipeUpdate",
    "SkillExecuteRequest",
    "SkillExecuteResponse",
    "SupermarketConnectionImport",
    "SupermarketConnectionRead",
    "SupermarketMappingCreate",
    "SupermarketMappingRead",
    "SupermarketSearchRequest",
    "SupermarketSearchResult",
    "SupermarketStoreRead",
]
