"""initial

Revision ID: 73b49b673d54
Revises: 
Create Date: 2026-03-06 02:16:01.135053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b49b673d54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('alert_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendarevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('PERSONAL', 'WORK', 'HEALTH', 'FINANCE', 'SOCIAL', name='eventtype'), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendaritem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'TASK', 'EVENT', 'SUBSCRIPTION', 'MEAL', name='calendarcategory'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'TASK', 'EVENT', 'SUBSCRIPTION', 'MEAL_PLAN', name='calendarsource'), nullable=False),
    sa.Column('source_ref_id', sa.Integer(), nullable=True),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_offsets_min', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendaritem_source_ref_id'), 'calendaritem', ['source_ref_id'], unique=False)
    op.create_table('financetransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('EXPENSE', 'INCOME', name='transactionkind'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groceryitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', name='habitfrequency'), nullable=False),
    sa.Column('target_per_period', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linearissuecache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linear_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assignee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_linear_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linearissuecache_identifier'), 'linearissuecache', ['identifier'], unique=False)
    op.create_index(op.f('ix_linearissuecache_linear_id'), 'linearissuecache', ['linear_id'], unique=False)
    op.create_index(op.f('ix_linearissuecache_project_linear_id'), 'linearissuecache', ['project_linear_id'], unique=False)
    op.create_table('linearprojectcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linear_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linearprojectcache_linear_id'), 'linearprojectcache', ['linear_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('NOTE', 'JOURNAL', 'IDEA', name='notekind'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantryitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_quantity', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('interval', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='subscriptioninterval'), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('autopay', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goalmilestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goalmilestone_goal_id'), 'goalmilestone', ['goal_id'], unique=False)
    op.create_table('grocerypantrysync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grocery_item_id', sa.Integer(), nullable=False),
    sa.Column('pantry_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['groceryitem.id'], ),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['pantryitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocerypantrysync_grocery_item_id'), 'grocerypantrysync', ['grocery_item_id'], unique=False)
    op.create_index(op.f('ix_grocerypantrysync_pantry_item_id'), 'grocerypantrysync', ['pantry_item_id'], unique=False)
    op.create_table('habitlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habitlog_habit_id'), 'habitlog', ['habit_id'], unique=False)
    op.create_table('mealplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_for', sa.Date(), nullable=False),
    sa.Column('slot', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', name='mealslot'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('servings_override', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_add_missing_ingredients', sa.Boolean(), nullable=False),
    sa.Column('synced_grocery_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealplan_recipe_id'), 'mealplan', ['recipe_id'], unique=False)
    op.create_table('recipeingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipeingredient_recipe_id'), 'recipeingredient', ['recipe_id'], unique=False)
    op.create_table('mealplancookconfirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pantry_consumption', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['mealplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealplancookconfirmation_meal_plan_id'), 'mealplancookconfirmation', ['meal_plan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealplancookconfirmation_meal_plan_id'), table_name='mealplancookconfirmation')
    op.drop_table('mealplancookconfirmation')
    op.drop_index(op.f('ix_recipeingredient_recipe_id'), table_name='recipeingredient')
    op.drop_table('recipeingredient')
    op.drop_index(op.f('ix_mealplan_recipe_id'), table_name='mealplan')
    op.drop_table('mealplan')
    op.drop_index(op.f('ix_habitlog_habit_id'), table_name='habitlog')
    op.drop_table('habitlog')
    op.drop_index(op.f('ix_grocerypantrysync_pantry_item_id'), table_name='grocerypantrysync')
    op.drop_index(op.f('ix_grocerypantrysync_grocery_item_id'), table_name='grocerypantrysync')
    op.drop_table('grocerypantrysync')
    op.drop_index(op.f('ix_goalmilestone_goal_id'), table_name='goalmilestone')
    op.drop_table('goalmilestone')
    op.drop_table('task')
    op.drop_table('subscription')
    op.drop_table('recipe')
    op.drop_table('pantryitem')
    op.drop_table('note')
    op.drop_index(op.f('ix_linearprojectcache_linear_id'), table_name='linearprojectcache')
    op.drop_table('linearprojectcache')
    op.drop_index(op.f('ix_linearissuecache_project_linear_id'), table_name='linearissuecache')
    op.drop_index(op.f('ix_linearissuecache_linear_id'), table_name='linearissuecache')
    op.drop_index(op.f('ix_linearissuecache_identifier'), table_name='linearissuecache')
    op.drop_table('linearissuecache')
    op.drop_table('habit')
    op.drop_table('groceryitem')
    op.drop_table('goal')
    op.drop_table('financetransaction')
    op.drop_index(op.f('ix_calendaritem_source_ref_id'), table_name='calendaritem')
    op.drop_table('calendaritem')
    op.drop_table('calendarevent')
    op.drop_table('budget')
    # ### end Alembic commands ###
